apiVersion: v1
kind: ConfigMap
metadata:
  name: tomcat-root
  namespace: apps
data:
  index.jsp: |
    <html>
    <body>
      <h1>Tomcat is running via Argo CD + Ingress</h1>
    </body>
    </html>
