apiVersion: v1
kind: ConfigMap
metadata:
  name: tomcat-root-app
  namespace: apps
data:
  index.jsp: |
    <%@ page contentType="text/html;charset=UTF-8" %>
    <html>
      <head><title>Tomcat GitOps</title></head>
      <body>
        <h1>Tomcat ROOT app is working âœ…</h1>
        <p>Served via Argo CD + Ingress</p>
      </body>
    </html>

  web.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <web-app xmlns="https://jakarta.ee/xml/ns/jakartaee"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="https://jakarta.ee/xml/ns/jakartaee
                                 https://jakarta.ee/xml/ns/jakartaee/web-app_5_0.xsd"
             version="5.0">

      <display-name>ROOT</display-name>

      <welcome-file-list>
        <welcome-file>index.jsp</welcome-file>
      </welcome-file-list>

    </web-app>
