apiVersion: v1
kind: ConfigMap
metadata:
  name: tomcat-root-app
  namespace: apps
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Tomcat via GitOps</title>
    </head>
    <body>
      <h1>âœ… Tomcat is running via Ingress</h1>
      <p>Deployed using Argo CD + GitOps</p>
    </body>
    </html>
