apiVersion: v1
kind: ConfigMap
metadata:
  name: tomcat-root-app
  namespace: apps
data:
  index.jsp: |
    <html>
      <body>
        <h1>Tomcat running via Argo CD + Ingress</h1>
        <p>GitOps setup is working âœ…</p>
      </body>
    </html>
