apiVersion: v1
kind: Service
metadata:
  name: tomcat
  namespace: apps
  labels:
    app: tomcat
spec:
  selector:
    app: tomcat
  ports:
    # Application traffic (Ingress â†’ Tomcat)
    - name: http
      port: 80
      targetPort: 8080

    # JVM / JMX metrics (Prometheus)
    - name: jmx
      port: 9404
      targetPort: 9404
